config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'
  post 'contacts/import'
  delete 'contacts/destroy'
  devise_for :users
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
require 'csv'

class Contact < ApplicationRecord
  belongs_to :user
  validates :name, :date_of_birth, :phone, :address, :credit_card, :franchise, :email, :user, presence: true
  validates :name, format: { with: /\A[[:alnum:] -]+\z/ }
  validates :credit_card, credit_card_number: {brands: [:amex, :diners, :discover, :jcb, :mastercard, :visa]} 

  def self.import(file, current_user)
    CSV.foreach(file.path, headers: true) do |row|
      detector = CreditCardValidations::Detector.new(row[4])
      franchise = detector.brand
      Contact.create(
        name: row[0],
        date_of_birth: row[1],
        phone: row[2],
        address: row[3],
        credit_card: row[4],
        franchise: franchise,
        email: row[5],
        user: current_user
      )
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = current_user.contacts.page(params[:page])
  end

  def import
    Contact.import(params[:file], current_user)
    redirect_to contacts_index_path, notice: 'imported'
    # @contacts = Array.new
    # myfile = params[:file]
    # @contacts = CSV.read(myfile.path)
  end

  def destroy
    current_user.contacts.delete_all
    redirect_to contacts_index_path, notice: 'deleted all contacts'
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def contact_fields
    ignore_attributes  = ['id', 'franchise', 'user_id', 'created_at', 'updated_at']
    attribute_names = Contact.attribute_names
    return (attribute_names - ignore_attributes)
  end
end

app/views/contacts/index.html.erb
<div class="d-grid gap-2 d-md-flex">
  <%= form_tag contacts_import_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import CSV file', class: 'btn btn-outline-secondary' %>
  <% end %>
  <%= link_to 'Delete all contacts', contacts_destroy_path, method: :delete, class: 'btn btn-outline-danger', type: "button" %>
</div>
<hr>

<table class="table table-striped">
  <thead>
    <%# <tr> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
      <%# <th><%= select_tag :contact_fields, options_for_select(contact_fields)</th> %>
    <%# </tr> %>
    <tr>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit Card</th>
      <th>Franchise</th>
      <th>Email</th>
      <th>User</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.date_of_birth.strftime('%Y %B %d') %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.credit_card.to_s.last(4) %></td>
        <td><%= contact.franchise %></td>
        <td><%= contact.email %></td>
        <td><%= contact.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @contacts %>

app/views/homepage/index.html.erb
<h1>Homepage#index</h1>
<p>Find me in app/views/homepage/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container">
      <% if notice %>
        <div id="flash">
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
        </div>
      <script>
        setTimeout();
      </script>
      <% end -%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Contact Importer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'Homepage', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contacts', contacts_index_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <% unless !user_signed_in? %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= link_to "#{current_user.email}", edit_user_registration_path, class: 'btn btn-outline-light', type: "submit" %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light', type: "submit" %>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</nav>